### ISSUE TITLE
训练问题请教

### ISSUE THREAD

**Issue by whjzsy** [vision4robotics/SiamAPN#1]
[符老师，您好，非常感谢您的团队共享代码，我在运行训练代码时，遇到下面问题，您能帮忙看看是哪里处问题了吗？非常感谢
[2021-03-22 21:35:48,552-rk0-train_apn++.py#214] init done
Traceback (most recent call last):
  File "train_apn++.py", line 279, in <module>
    main()
  File "train_apn++.py", line 217, in main
    cfg.merge_from_file(args.cfg)
  File "/home/wanghaijun/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/wanghaijun/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/wanghaijun/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/wanghaijun/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 456, in _merge_a_into_b
    v = _check_and_coerce_cfg_value_type(v, b[k], k, full_key)
  File "/home/wanghaijun/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 513, in _check_and_coerce_cfg_value_type
    original_type, replacement_type, original, replacement, full_key
ValueError: Type mismatch (<class 'str'> vs. <class 'int'>) with values ( vs. 0) for config key: TRAIN.PRETRAINED

**Comment by whjzsy** [comment]
符老师好，上面问题已经解决，出现下面新的问题，     我只采用了VID和COCO两个数据集                                                                                                               
 error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/vid/crop511/c/ILSVRC2015_train_00629003/000267.00.x.jpg
error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/vid/crop511/c/ILSVRC2015_train_00629003/000279.00.x.jpg
error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/coco/crop511/train2017/000000172509/000000.23.x.jpg
error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/coco/crop511/train2017/000000172509/000000.23.x.jpg

**Comment by whjzsy** [comment]
对代码进行了简单修改，问题初步解决了。

**Comment by triumph693** [comment]
> 符老师好，上面问题已经解决，出现下面新的问题， 我只采用了VID和COCO两个数据集 error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/vid/crop511/c/ILSVRC2015_train_00629003/000267.00.x.jpg error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/vid/crop511/c/ILSVRC2015_train_00629003/000279.00.x.jpg error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/coco/crop511/train2017/000000172509/000000.23.x.jpg error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/coco/crop511/train2017/000000172509/000000.23.x.jpg

您好，我也遇到了同样的问题，请问您是怎么解决的呢，期待您的回复

**Comment by triumph693** [comment]
> 符老师好，上面问题已经解决，出现下面新的问题， 我只采用了VID和COCO两个数据集 error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/vid/crop511/c/ILSVRC2015_train_00629003/000267.00.x.jpg error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/vid/crop511/c/ILSVRC2015_train_00629003/000279.00.x.jpg error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/coco/crop511/train2017/000000172509/000000.23.x.jpg error image: /media/wanghaijun/FED875CED87585A5/pysot/training_dataset/coco/crop511/train2017/000000172509/000000.23.x.jpg

您好，我也遇到了同样的问题，请问您是怎么解决的呢，期待您的回复
