### ISSUE TITLE
关于test

### ISSUE THREAD

**Issue by leidriver201120** [vision4robotics/SiamAPN#10]
我看到代码里toolkit/datasets/uav10fps.py这里面的25行左右，img和txt实际运行的话，会遇到No such file or directory: '../test_dataset/UAV123_10fps/anno/bird1.txt这个报错，我发现这是因为数据集中有data_seq/bird1这个文件夹，但是标注文件夹里是没有anno/bird.txt这个文件的，只有bird1_1.txt、bird1_2.txt、bird1_3.txt三个文件，那请问你们在这里是怎么处理的呢

**Comment by ziangcao0312** [comment]
我们这里是把数据集拆开后来进行测试的，当然也可以写json文件。

**Comment by JackHe1999** [comment]
> 我们这里是把数据集拆开后来进行测试的，当然也可以写json文件。

你好，关于“数据集拆开后来进行测试”这个操作可以详细说明一下吗

**Comment by 102447** [comment]
请问是根据什么标准进行数据集拆分的，bird1文件夹有813帧图像，三个txt文件一共有609帧注释，他们是顺次对应的关系吗？
