### ISSUE TITLE
测试结果

### ISSUE THREAD

**Issue by triumph693** [vision4robotics/SiamAPN#13]
您好，我想问一下，您最后话的与其他跟踪器的对比实验图需要其他跟踪算法的测试结果的,txt文件，请问您能分享一下么，不然是不是还得每个算法都要自己训练和测试呢，期待您的回复

**Comment by vision4robotics** [comment]
请参考我们的其他工作 https://github.com/vision4robotics/DCFTracking4UAV，我们所有的跟踪结果是要用官方model和code测试出来的。

**Comment by xyl-507** [comment]
@vision4robotics 
作者您好！
感谢你们的巨大贡献。我想请问一下对比实验中的txt文件可以提供下吗？您给的网站中https://github.com/vision4robotics/DCFTracking4UAV 里比较新的算法较少（如您论文中的SiamRPN++，SiamFC++等），自己想用这些算法对比一下，不知道能否提供一下？
十分感谢！
