### ISSUE TITLE
gamma值

### ISSUE THREAD

**Issue by bobo-liang** [vision4robotics/SiamAPN#14]
您好，请问在pointbranch 中的gamma 参数一不更新吗？调了几次一直为0

**Comment by ziangcao0312** [comment]
感谢您的关注，在我们的方法中gamma参数是残差连接的形式发挥作用是更新的。但由于经过注意力操作后的特征图值为（-10，10），而x值域为（0，2），为了避免负影响我们初始化为0，而由于值域的差距导致gamma值是比较小的。当然也可以尝试使用其他初始化的方式，来训练gamma值。
