### ISSUE TITLE
UAVTrack112

### ISSUE THREAD

**Issue by FreeZhang96** [vision4robotics/SiamAPN#2]
Hi Dr. Fu,
Thanks for your great work! We want to use the newly built benchmark UAVTrack112. Could you provide the details about the benchmark, such as attributes and citation format?
Sorry for disturbing you and hope you can help me with it.
Thanks!

**Comment by vision4robotics** [comment]
I am sorry to tell you that the UAVTrack112 hasn't been accepted. Therefore, there is no formal citation format. As for the attributes, when our paper is accepted, we will explain them detailedly in Github. Please be patient.
