### ISSUE TITLE
New datasets

### ISSUE THREAD

**Issue by xyl-507** [vision4robotics/SiamAPN#4]
感谢作者的杰出贡献：
请问一下，如果我想在**UAVDT**、**DTB70**上测试该模型，.json文件应该怎么生成？Pysot没有相关的代码，不知道作者能不能分享一下？

**Comment by JAYCHOU2020** [comment]
> 感谢作者的杰出贡献：
> 请问一下，如果我想在**UAVDT**、**DTB70**上测试该模型，.json文件应该怎么生成？Pysot没有相关的代码，不知道作者能不能分享一下？

同学你训练成功了吗

**Comment by whjzsy** [comment]
感谢作者的杰出贡献：
请问一下，如果我想在UAVDT、DTB70上测试该模型，.json文件应该怎么生成？Pysot没有相关的代码，不知道作者能不能分享一下？

同学你训练成功了吗

SiamAPN，HiFT训练成功，但是没有使用GOT数据，HiFT测试结果不是很理想（训练数据为VID,COCO,DET,UYB,YOUTUBEBB），没有找到原因，也许是没有用GOT训练数据的原因。

**Comment by JAYCHOU2020** [comment]
> 试
可以训练多类别的吗？你的dataset是如何准备的呢？readme里面没找到相关的介绍，想向您请教一下，谢谢啦

**Comment by JAYCHOU2020** [comment]
> 感谢作者的杰出贡献：
> 请问一下，如果我想在UAVDT、DTB70上测试该模型，.json文件应该怎么生成？Pysot没有相关的代码，不知道作者能不能分享一下？
> 
> 同学你训练成功了吗
> 
> SiamAPN，HiFT训练成功，但是没有使用GOT数据，HiFT测试结果不是很理想（训练数据为VID,COCO,DET,UYB,YOUTUBEBB），没有找到原因，也许是没有用GOT训练数据的原因。

可以训练多类别的吗？你的dataset是如何准备的呢？readme里面没找到相关的介绍，想向您请教一下，谢谢啦

**Comment by JAYCHOU2020** [comment]
> 感谢作者的杰出贡献：
> 请问一下，如果我想在UAVDT、DTB70上测试该模型，.json文件应该怎么生成？Pysot没有相关的代码，不知道作者能不能分享一下？
> 
> 同学你训练成功了吗
> 
> SiamAPN，HiFT训练成功，但是没有使用GOT数据，HiFT测试结果不是很理想（训练数据为VID,COCO,DET,UYB,YOUTUBEBB），没有找到原因，也许是没有用GOT训练数据的原因。

就是我想训练自己制作好的MOT数据集，具体的traindataset文件应该如何准备呢？

**Comment by whjzsy** [comment]
感谢作者的杰出贡献：
请问一下，如果我想在UAVDT、DTB70上测试该模型，.json文件应该怎么生成？Pysot没有相关的代码，不知道作者能不能分享一下？

同学你训练成功了吗

SiamAPN，HiFT训练成功，但是没有使用GOT数据，HiFT测试结果不是很理想（训练数据为VID,COCO,DET,UYB,YOUTUBEBB），没有找到原因，也许是没有用GOT训练数据的原因。

就是我想训练自己制作好的MOT数据集，具体的traindataset文件应该如何准备呢？

可以参考siamban里的代码进行准备

**Comment by vision4robotics** [comment]
1. 我们并没有生成json文件，而是在线读取数据集格式生成对应的字典，相关文件在pysot/toolkit/datasets中，我们使用简单for循环实现简单易读。
2. 训练条件如果和我们是一样的话，应该可以保证测试效果，因为我们控制了随机种子。
3. 目前我们的两个跟踪器只是针对SOT，具体如何训练MOT数据集并没有相关经验。

**Comment by xyl-507** [comment]
> 1. 我们并没有生成json文件，而是在线读取数据集格式生成对应的字典，相关文件在pysot/toolkit/datasets中，我们使用简单for循环实现简单易读。
> 2. 训练条件如果和我们是一样的话，应该可以保证测试效果，因为我们控制了随机种子。
> 3. 目前我们的两个跟踪器只是针对SOT，具体如何训练MOT数据集并没有相关经验。

作者您好。我看见你们在readme中介绍到 the tracking results_v2 (code: j4t5) of UAV123@10fps, UAV20L, VisDrone2018-SOT-test and UAVTrack112 are also provided.
你们测试结果里有VisDrone2018-SOT-test and UAVTrack112，请问你们是在pysot这个平台测试的吗？如果是的话，这个平台好像测试时是需要json文件的，不知道能否提供一下？谢谢

**Comment by cuikf** [comment]
> 感谢作者的杰出贡献： 请问一下，如果我想在UAVDT、DTB70上测试该模型，.json文件应该怎么生成？Pysot没有相关的代码，不知道作者能不能分享一下？
> 
> 同学你训练成功了吗
> 
> SiamAPN，HiFT训练成功，但是没有使用GOT数据，HiFT测试结果不是很理想（训练数据为VID,COCO,DET,UYB,YOUTUBEBB），没有找到原因，也许是没有用GOT训练数据的原因。
> 
> 就是我想训练自己制作好的MOT数据集，具体的traindataset文件应该如何准备呢？
> 
> 可以参考siamban里的代码进行准备

您好，我想请问下您的环境是怎么配置的？我运行python test.py报错找不到pysot，但是用export PYTHONPATH= 也报错

**Comment by vision4robotics** [comment]
应该是 export PYTHONPATH=**your path**:$PYTHONPATH就可以添加目录了

**Comment by LLLLLLLloser** [comment]
> 1. 我们并没有生成json文件，而是在线读取数据集格式生成对应的字典，相关文件在pysot/toolkit/datasets中，我们使用简单for循环实现简单易读。
> 2. 训练条件如果和我们是一样的话，应该可以保证测试效果，因为我们控制了随机种子。
> 3. 目前我们的两个跟踪器只是针对SOT，具体如何训练MOT数据集并没有相关经验。

您好！！我用pysot/toolkit/datasets的测试UAV20L，报错回显为FileNotFoundError: [Errno 2] No such file or directory: '/data1/dataset/UAV123/anno/UAV123.txt'我应该怎样解决

**Comment by LLLLLLLloser** [comment]
> 感谢作者的杰出贡献： 请问一下，如果我想在UAVDT、DTB70上测试该模型，.json文件应该怎么生成？Pysot没有相关的代码，不知道作者能不能分享一下？
> 
> 同学你训练成功了吗
> 
> SiamAPN，HiFT训练成功，但是没有使用GOT数据，HiFT测试结果不是很理想（训练数据为VID,COCO,DET,UYB,YOUTUBEBB），没有找到原因，也许是没有用GOT训练数据的原因。

我在HIFT上对GOT10K进行了70个Epoch的训练，有70个结果文件。我应该怎样选取最好的一轮
