### ISSUE TITLE
About  run with tesorrt in NVIDIA jetson agx

### ISSUE THREAD

**Issue by Youjiangbaba** [vision4robotics/SiamAPN#6]
It's a great job and  can reach 180fps with Pytorch on 2080ti.  Will you open source the tensort deployment code running on Jetson?

**Comment by CcCc-ceil** [comment]
Thanks for your attention. Note that this project can be implemented on AGX directly with a speed of ~30fps without TensorRT. The TensorRT version will be released in future work.
